# .travis.yml
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  code_climate:
    repo_token: 663d8c96e32c89c70504dec16c2fc61374251f28308b804d7ca1cd918c71a643

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit

after_script:
  - vendor/bin/test-reporter
